name: "Podcast Generator"
author: "TheWhiteWolf3303"
description: "Generates a feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "pink"
inputs:
  email:
    description: The committer's email address
    required: true
    default: "github-actions@localhost"
  name:
    description: The committer's name
    required: true
    default: "github-actions"

